# Railway Configuration for TrueCivic API
# This deploys the FastAPI backend service

[build]
builder = "DOCKERFILE"
dockerfilePath = "api.dockerfile"
watchPatterns = ["api/**", "src/**", "requirements.txt"]

[deploy]
startCommand = "python scripts/run_migrations.py && uvicorn api.main:app --host 0.0.0.0 --port ${PORT:-8000}"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[healthcheck]
path = "/health"
timeout = 30
interval = 30
