[build]
builder = "NIXPACKS"
buildCommand = "cd frontend && npm install && npm run build"
watchPatterns = ["frontend/**"]

[deploy]
startCommand = "cd frontend && npm run start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[healthcheck]
path = "/"
timeout = 100
interval = 30
