# Generated by GitHub Copilot GPT-5-Codex on 2025-10-26

from django.db import migrations


SQL_DROP_COLUMN = """
DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = current_schema()
          AND table_name = 'rag_knowledgechunk'
          AND column_name = 'embedding'
    ) THEN
        ALTER TABLE rag_knowledgechunk DROP COLUMN embedding;
    END IF;
END $$;
"""

SQL_ADD_JSON_COLUMN = """
ALTER TABLE rag_knowledgechunk
    ADD COLUMN IF NOT EXISTS embedding jsonb DEFAULT '[]'::jsonb;
UPDATE rag_knowledgechunk
   SET embedding = COALESCE(embedding, '[]'::jsonb);
ALTER TABLE rag_knowledgechunk
    ALTER COLUMN embedding SET DEFAULT '[]'::jsonb;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("rag", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(sql=SQL_DROP_COLUMN, reverse_sql=""),
                migrations.RunSQL(sql=SQL_ADD_JSON_COLUMN, reverse_sql=""),
            ],
            state_operations=[],
        ),
    ]
